services:
  # Backend API Service
  - type: web
    name: heart-disease-backend
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      python app.py
    envVars:
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: PLATFORM_MAX_SIZE
        value: 209715200
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://heart-disease-frontend.onrender.com
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: 10000
    healthCheckPath: /health

  # Frontend Static Site
  - type: web
    name: heart-disease-frontend
    env: static
    plan: free
    buildCommand: |
      cd frontend
      npm ci --only=production
      npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
